### ISSUE TITLE
Mobile Layout not showing logo.

### ISSUE THREAD

**Issue by RossMdevs** [kchaney1508/backlot.city#3]
The mobile variation (Safari iOS 17.x) is not showing any logo/text.

**Comment by RossMdevs** [comment]
![unnamed](https://github.com/kchaney1508/backlot.city/assets/37253938/662bd54e-1c95-486f-bc5d-97b1b88ebeef)

**Comment by kchaney1508** [comment]
Fixed @ https://github.com/kchaney1508/backlot.city/commit/78e91a6ecafbce52ae93d8ea0f431d7ae9dff34b

iPhone 11 Pro:
![image](https://github.com/kchaney1508/backlot.city/assets/107610683/5337aabc-ed4d-4bab-9cc3-d32a5311502f)
